export { defineTaxonomy } from './contracts/define-taxonomy';
export { provideTaxonomy, provideTaxonomyCatalog } from './contracts/taxonomy-provider';
export { validateTaxonomyModule } from './validation/validate-taxonomy-module';

export type {
  FactPresentation,
  DashboardMediaDefinition,
  DashboardSectionDefinition,
  DashboardTargetKind,
  DashboardWidgetDefinition,
  DimensionalProjectionDefinition,
  DomainCoverage,
  EntityReference,
  HierarchicalProjectionDefinition,
  HierarchyEdge,
  HierarchyLayerDefinition,
  HierarchyLayerSlot,
  HierarchyNode,
  HierarchyNodeMeasure,
  HierarchyViewPreset,
  LivingCompositionContent,
  NodeMeasureEncoding,
  NumericRange,
  ProfileSectionViewModel,
  RelatedEntity,
  ResolvedIcon,
  SourceReference,
  TaxonomyContent,
  TaxonomyContentSection,
  TaxonomyContentBundle,
  TaxonomyContentProvider,
  TaxonomyDashboardDefinition,
  TaxonomyDimension,
  TaxonomyEntry,
  TaxonomyFacet,
  TaxonomyGroup,
  TaxonomyMeta,
  TaxonomyModule,
  TaxonomyLegacyImporter,
  TaxonomyPersistenceDefinition,
  TaxonomyPresentation,
  TaxonomyProfileDefinition,
  TaxonomyThemePreset as TaxonomyTheme,
  TaxonOccurrence,
  ProjectedNodeMeasure,
  TaxonomyVocabulary,
} from './contracts/taxonomy';
export type { TaxonomyCatalogItem } from './contracts/taxonomy-provider';
export type {
  TaxonomyValidationIssue,
  TaxonomyValidationResult,
  TaxonomyValidationResult as ValidationReport,
} from './validation/validate-taxonomy-module';
